# Random Projections
Es una técnica utilizada para reducir la dimensionalidad de un conjunto de puntos que se encuentran en el espacio euclidiano. Los métodos de proyección aleatoria son métodos potentes conocidos por su simplicidad y resultados menos erróneos en comparación con otros métodos. De acuerdo con los resultados experimentales, la proyección aleatoria preserva bien las distancias, pero los resultados empíricos son escasos.

In [1]:
import numpy as np
import random
import matplotlib.pyplot as plot
import math

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [3]:
data = np.genfromtxt(fname='../../datasets/cancer.txt', delimiter=',')
data = np.delete(data, np.s_[0], axis=1)
data = data[~np.isnan(data).any(axis=1)] #Eliminamos los nan

labels = data[:, -1]
features = data[:, :-1]

X_train, X_valid, Y_train, Y_valid = train_test_split(features, labels, test_size = 0.1)

In [4]:
print(X_train)
print(X_train.shape)

[[ 3.  1.  1. ...  3.  1.  1.]
 [ 1.  1.  1. ...  3.  1.  1.]
 [ 8. 10.  8. ...  7.  7.  1.]
 ...
 [ 3.  1.  1. ...  2.  1.  1.]
 [ 3.  1.  1. ...  2.  1.  1.]
 [ 8.  9.  9. ...  7.  7.  1.]]
(614, 9)


In [5]:
scaler = StandardScaler()

x_train_final = scaler.fit_transform(X_train)
x_valid_final = scaler.transform(X_valid)


print(x_train_final)
print(x_train_final.shape)

[[-0.51542599 -0.70343474 -0.7469279  ... -0.18490008 -0.61360094
  -0.34836428]
 [-1.21947839 -0.70343474 -0.7469279  ... -0.18490008 -0.61360094
  -0.34836428]
 [ 1.24470502  2.20395522  1.58274998 ...  1.44275077  1.35376709
  -0.34836428]
 ...
 [-0.51542599 -0.70343474 -0.7469279  ... -0.59181279 -0.61360094
  -0.34836428]
 [-0.51542599 -0.70343474 -0.7469279  ... -0.59181279 -0.61360094
  -0.34836428]
 [ 1.24470502  1.88091189  1.91556111 ...  1.44275077  1.35376709
  -0.34836428]]
(614, 9)
