# Standard Scaler
Esta técnica es útil cuando se quiere comparar datos que corresponden a diferentes unidades, transformará sus datos de modo que su distribución tendrá un valor medio 0 y una desviación estándar de 1.

In [2]:
import numpy as np
import random
import matplotlib.pyplot as plot
import math

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [4]:
data = np.genfromtxt(fname='../../datasets/cancer.txt', delimiter=',')
data = np.delete(data, np.s_[0], axis=1)
data = data[~np.isnan(data).any(axis=1)] #Eliminamos los nan

labels = data[:, -1]
features = data[:, :-1]

X_train, X_valid, Y_train, Y_valid = train_test_split(features, labels, test_size = 0.1)

In [5]:
print(X_train)
print(X_train.shape)

[[8. 3. 3. ... 3. 2. 1.]
 [3. 1. 1. ... 1. 1. 1.]
 [2. 1. 1. ... 1. 1. 1.]
 ...
 [7. 5. 3. ... 7. 5. 5.]
 [4. 1. 1. ... 3. 1. 1.]
 [3. 1. 1. ... 3. 1. 1.]]
(614, 9)


In [6]:
scaler = StandardScaler()

x_train_final = scaler.fit_transform(X_train)
x_valid_final = scaler.transform(X_valid)

print(x_train_final)
print(x_train_final.shape)

[[ 1.24382223 -0.0723981  -0.0814919  ... -0.19375998 -0.29985444
  -0.35358906]
 [-0.52729755 -0.71200148 -0.74422071 ... -1.00032695 -0.62456453
  -0.35358906]
 [-0.88152151 -0.71200148 -0.74422071 ... -1.00032695 -0.62456453
  -0.35358906]
 ...
 [ 0.88959828  0.56720527 -0.0814919  ...  1.41937396  0.67427585
   1.86175464]
 [-0.17307359 -0.71200148 -0.74422071 ... -0.19375998 -0.62456453
  -0.35358906]
 [-0.52729755 -0.71200148 -0.74422071 ... -0.19375998 -0.62456453
  -0.35358906]]
(614, 9)
