# Principal Component Analysis
Reduccion de dimensiones. Cuando tenes una gran cantidad de features, se achica la cantidad sin perder la correlacion entre los datos.
Por lo general, si es muy grande, primero aplicamos Random Projections y luego PCA.

In [43]:
import numpy as np
import random
import matplotlib.pyplot as plot
import math
from sklearn.model_selection import train_test_split
from  sklearn.decomposition import PCA

In [44]:
data = np.genfromtxt(fname='../../datasets/cancer.txt', delimiter=',')
data = np.delete(data, np.s_[0], axis=1)
data = data[~np.isnan(data).any(axis=1)] #Eliminamos los nan

labels = data[:, -1]
features = data[:, :-1]

X_train, X_valid, Y_train, Y_valid = train_test_split(features, labels, test_size = 0.1)

In [45]:
print(X_train)
print(X_train.shape)

[[ 2.  1.  1. ...  2.  1.  1.]
 [ 3.  5.  7. ...  7. 10.  7.]
 [ 5.  1.  1. ...  2.  1.  1.]
 ...
 [ 4.  1.  1. ...  2.  1.  1.]
 [ 3. 10.  3. ...  5.  1.  4.]
 [ 5.  1.  3. ...  2.  1.  1.]]
(614, 9)


In [46]:
pca = PCA(n_components = 0.95)

x_train_final = pca.fit_transform(X_train)
x_valid_final = pca.transform(X_valid)

print(x_train_final)
print(x_train_final.shape)

[[-5.60436455  0.23195758  0.71575231 ...  0.31703556  0.06872281
   0.14803184]
 [11.43908416  1.82113214  5.59998253 ... -1.50330728  3.8070408
   1.30250454]
 [-4.72873127  0.07237989 -1.83076    ... -0.8840029  -0.21599178
   0.25974292]
 ...
 [-5.27340217 -0.09987218 -1.02402883 ... -0.72781672 -0.52712348
   0.16416085]
 [ 8.38014524 -3.92178204  4.97928159 ...  0.09194993  2.22191769
  -0.04217728]
 [-3.94443924  0.38620755 -2.03151134 ... -0.14236106 -0.40952756
  -0.25743771]]
(614, 7)
