#### Chest X-Ray Images (Pneumonia)

URL: https://www.kaggle.com/paultimothymooney/chest-xray-pneumonia

In [1]:
import numpy as np


In [39]:
#Mezclar
import numpy as np
x = np.arange(10)
y = np.arange(9, -1, -1)

print(x.shape[0])

print(y)
s = np.arange(x.shape[0])
print(s)
np.random.shuffle(s)

print(s)
print(x[s])
print(y[s])

10
[9 8 7 6 5 4 3 2 1 0]
[0 1 2 3 4 5 6 7 8 9]
[5 9 3 2 0 6 1 4 7 8]
[5 9 3 2 0 6 1 4 7 8]
[4 0 6 7 9 3 8 5 2 1]


In [78]:
np.zeros(3)

array([1., 1., 1.])

In [127]:
import os
import skimage
from skimage.transform import resize
from PIL import Image
from keras.utils import to_categorical

def get_x_and_y(type_dataset, type_label):
    x = []
    path = './datasets/' + type_dataset + "/" + type_label + "/"
    files = os.listdir(path)
    for file in files:
        if os.path.splitext(path + file)[1] == '.jpeg':
            img = np.array(Image.open(path + file))
            img = np.asarray(skimage.transform.resize(img, (150, 150, 3)))
            x.append(img)
    x = np.asarray(x)
    y = np.zeros(x.shape[0]) if type_label == 'NORMAL' else np.ones(x.shape[0])
    y = to_categorical(y)
    return x, y


In [128]:
train_normal_x, train_normal_y = get_x_and_y('train', 'NORMAL')
train_pneumonia_x, train_pneumonia_y = get_x_and_y('train', 'PNEUMONIA')

/anaconda3/lib/python3.6/site-packages/skimage/transform/_warps.py:84: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "


In [129]:
print(train_normal_x.shape)
print(train_normal_y.shape)

(1342, 150, 150, 3)
(1342, 1)
